name: ZipSite Generate from Airtable

on:
  workflow_dispatch:
    inputs:
      recordId:
        description: "Airtable record ID (e.g., recXXXXXXXXXXXXXX)"
        required: true
        type: string
  repository_dispatch:
    types: [zipsite_generate]

jobs:
  build-from-brief:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    env:
      RID: ${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.recordId) || github.event.inputs.recordId }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Fetch Airtable brief
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE: ${{ secrets.AIRTABLE_PROJECTS_TABLE }}
          RECORD_ID: ${{ env.RID }}
        run: node scripts/fetch-brief.js

      - name: Plan with DeepSeek # CHANGED
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }} # CHANGED
        run: node scripts/plan.js

      - name: Generate pages with DeepSeek # CHANGED
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }} # CHANGED
        run: node scripts/gen-pages.js

      - name: Create build branch
        id: branch
        run: |
          BR="build-${RID}"
          git config user.name "zipsite-bot"
          git config user.email "bot@zipsitestudio.com"
          git checkout -B "$BR"
          echo "BRANCH=$BR" >> $GITHUB_OUTPUT

      - name: Commit files
        run: |
          git add -A
          git commit -m "auto: plan + scaffold from Airtable ${RID}" || echo "No changes to commit"
          git push -u origin "${{ steps.branch.outputs.BRANCH }}" || true

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Auto build for ${{ env.RID }}"
          body: "Generated from Airtable record ${{ env.RID }}"
          branch: ${{ steps.branch.outputs.BRANCH }}
          base: main
          delete-branch: false
          commit-message: "auto: plan + scaffold from Airtable ${{ env.RID }}"
