name: ZipSite Generate from Airtable

on:
  workflow_dispatch:
    inputs:
      recordId:
        description: "Airtable record ID (e.g., recXXXXXXXXXXXXXX)"
        required: true
        type: string
  repository_dispatch:
    types: [zipsite_generate]

jobs:
  build-from-brief:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Fetch Airtable Brief
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE: ${{ secrets.AIRTABLE_PROJECTS_TABLE }}
          RECORD_ID: ${{ github.event.inputs.recordId || github.event.client_payload.recordId }}
        run: node scripts/fetch-brief.js

      - name: Plan with Groq
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: node scripts/plan.js

      - name: List files in plan directory
        run: ls -R plan

      - name: Generate Pages with Groq
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          node scripts/gen-pages.js
          mkdir -p components

      - name: Install AI-Generated Dependencies
        run: |
          if [ -f "dependencies.json" ]; then
            echo "Found dependencies.json, installing packages..."
            PACKAGES=$(jq -r '.dependencies | join(" ")' dependencies.json)
            if [ -n "$PACKAGES" ]; then
              npm install $PACKAGES
            else
              echo "No packages listed in dependencies.json."
            fi
          else
            echo "No dependencies.json file found, skipping step."
          fi
      
      - name: Run QA Agent
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: node scripts/qa-agent.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            sites/
            plan/
            brief.json
            dependencies.json
            package.json
            package-lock.json
          commit-message: "auto: plan + scaffold from Airtable record"
          branch: "build-${{ github.event.inputs.recordId || github.event.client_payload.recordId }}"
          delete-branch: true
          title: "Auto-build for Airtable Record"
          body: "This PR was auto-generated by the ZipSite workflow for record `${{ github.event.inputs.recordId || github.event.client_payload.recordId }}`."
          author: "zipsite-bot <bot@zipsitestudio.com>"
          committer: "zipsite-bot <bot@zipsitestudio.com>"
