name: ZipSite Generate from Airtable

on:
  workflow_dispatch:
    inputs:
      recordId:
        description: "Airtable record ID (e.g., recXXXXXXXXXXXXXX)"
        required: true
        type: string
  repository_dispatch:
    types: [zipsite_generate]

jobs:
  build-from-brief:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Fetch Airtable Brief
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE: ${{ secrets.AIRTABLE_PROJECTS_TABLE }}
          RECORD_ID: ${{ github.event.inputs.recordId || github.event.client_payload.recordId }}
        run: node scripts/fetch-brief.js

      - name: Plan with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: node scripts/plan.js

      - name: Generate Pages with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: node scripts/gen-pages.js

      - name: Create Build Branch
        id: branch
        run: |
          RECORD_ID="${{ github.event.inputs.recordId || github.event.client_payload.recordId }}"
          BRANCH_NAME="build-${RECORD_ID}"
          git config user.name "zipsite-bot"
          git config user.email "bot@zipsitestudio.com"
          git checkout -B "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        
      - name: Commit Files
        run: |
          git add -A
          git commit -m "auto: plan + scaffold from Airtable record" || echo "No changes to commit"
          git push -u origin ${{ steps.branch.outputs.branch_name }} --force

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Auto-build for Airtable Record"
          body: "This PR was auto-generated by the ZipSite workflow for record `${{ github.event.inputs.recordId || github.event.client_payload.recordId }}`."
          branch: ${{ steps.branch.outputs.branch_name }}
          base: main
          delete-branch: true
