name: ZipSite Generate from Airtable

on:
  workflow_dispatch:
    inputs:
      recordId:
        description: "Airtable record ID (e.g., recXXXXXXXXXXXXXX)"
        required: true
        type: string
  repository_dispatch:
    types: [zipsite_generate]

jobs:
  build-from-brief:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Fetch Airtable Brief
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE: ${{ secrets.AIRTABLE_PROJECTS_TABLE }}
          RECORD_ID: ${{ github.event.inputs.recordId || github.event.client_payload.recordId }}
        run: node scripts/fetch-brief.js

      - name: Plan with Groq
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: node scripts/plan.js

      - name: Generate Pages with Groq
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: node scripts/gen-pages.js

      # The 'Create Build Branch' and 'Commit Files' steps have been removed.
      # The logic is now handled by the single step below.

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            app/
            components/
            plan/
            brief.json
          commit-message: "auto: plan + scaffold from Airtable record"
          branch: "build-${{ github.event.inputs.recordId || github.event.client_payload.recordId }}"
          delete-branch: true
          title: "Auto-build for Airtable Record"
          body: "This PR was auto-generated by the ZipSite workflow for record `${{ github.event.inputs.recordId || github.event.client_payload.recordId }}`."
          author: "zipsite-bot <bot@zipsitestudio.com>"
          committer: "zipsite-bot <bot@zipsitestudio.com>"
