name: ZipSite Generate from Airtable

on:
  workflow_dispatch:
    inputs:
      recordId:
        description: "Airtable record ID (e.g., recXXXXXXXXXXXXXX)"
        required: true
        type: string
  repository_dispatch:
    types: [zipsite_generate]

jobs:
  build-from-brief:
    runs-on: ubuntu-latest
    concurrency: build-${{ env.RID }}
    permissions:
      contents: write
      pull-requests: write

    env:
      RID: ${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.recordId) || github.event.inputs.recordId }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Fetch Airtable brief
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE: ${{ secrets.AIRTABLE_PROJECTS_TABLE }}
          RECORD_ID: ${{ env.RID }}
        run: node scripts/fetch-brief.js

      - name: Validate API Keys
        run: |
          echo "Validating API keys..."
          
          # Check Google API Key
          if [ -z "${{ secrets.GOOGLE_API_KEY }}" ]; then
            echo "❌ ERROR: GOOGLE_API_KEY secret is not set"
            exit 1
          else
            echo "✅ GOOGLE_API_KEY is set"
          fi
          
          # Check Airtable credentials
          if [ -z "${{ secrets.AIRTABLE_API_KEY }}" ]; then
            echo "❌ ERROR: AIRTABLE_API_KEY secret is not set"
            exit 1
          else
            echo "✅ AIRTABLE_API_KEY is set"
          fi
          
          if [ -z "${{ secrets.AIRTABLE_BASE_ID }}" ]; then
            echo "❌ ERROR: AIRTABLE_BASE_ID secret is not set"
            exit 1
          else
            echo "✅ AIRTABLE_BASE_ID is set"
          fi
          
          if [ -z "${{ secrets.AIRTABLE_PROJECTS_TABLE }}" ]; then
            echo "❌ ERROR: AIRTABLE_PROJECTS_TABLE secret is not set"
            exit 1
          else
            echo "✅ AIRTABLE_PROJECTS_TABLE is set"
          fi
          
          echo "All API keys validated successfully"

      - name: Plan with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: node scripts/plan.js

      - name: Generate pages with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: node scripts/gen-pages.js

      - name: Create build branch
        id: branch
        run: |
          BRANCH_NAME="build-${RID}-$(date +%s)"
          git config user.name "zipsite-bot"
          git config user.email "bot@zipsitestudio.com"
          git checkout -B "$BRANCH_NAME"
          echo "BRANCH=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Commit files
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "auto: plan + scaffold from Airtable ${RID}"
            git push -u origin "${{ steps.branch.outputs.BRANCH }}"
          fi

      - name: Open Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Auto build for ${{ env.RID }}"
          body: "Generated from Airtable record ${{ env.RID }}"
          branch: ${{ steps.branch.outputs.BRANCH }}
          base: main
          delete-branch: false
          commit-message: "auto: plan + scaffold from Airtable ${RID}"
